In [2]:
import pandas as pd

In [3]:
df1= pd.read_csv("Art  Design.csv")

In [4]:
df1.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,"Canva: Design, Photo & Video",Canva,Art & Design,27 MB,4.4,66L,10Cr+,3+
1,2,Sketchbook,Sketchbook,Art & Design,100 MB,4.2,4L,5Cr+,3+
2,3,ibis Paint X,ibis inc.,Art & Design,27 MB,4.3,19L,10Cr+,3+
3,4,Thumbnail Maker For YouTube,Content Arcade Apps,Art & Design,13 MB,4.2,1L,50L+,3+
4,5,Glitter dress coloring and drawing book for Kids,BaramGames,Art & Design,56 MB,4.0,33T,1Cr+,3+

In [5]:
df2= pd.read_csv("Auto  Vehicles.csv")

In [6]:
df2.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,RTO Vehicle Information,Learn English In Hindi - Translator & Dictionary,Auto & Vehicles,21 MB,4.5,1L,1Cr+,3+
1,2,"Vahak: Book Online Truck, Load",Most Trusted Transporters from All India.,Auto & Vehicles,17 MB,3.8,3T,10L+,3+
2,3,"CARS24® – Buy Used Cars Online, Sell Car in 1 ...",CARS24 Services Private Limited,Auto & Vehicles,33 MB,4.4,1L,1Cr+,3+
3,4,BlackBuck Boss,BlackBuck,Auto & Vehicles,39 MB,4.1,27T,10L+,3+
4,5,CarDekho:New & Second Hand Car,Girnar Software Pvt. Ltd.,Auto & Vehicles,18 MB,4.5,1L,1Cr+,3+

In [7]:
df3= pd.read_csv("Beauty.csv")

In [8]:
df3.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,Dress Up Royal Princess Doll,winkypinky,Beauty,42 MB,3.7,11T,10L+,3+
1,2,Beauty Camera : You Makeover Plus Selfie,SB Gallery Studio,Beauty,16 MB,3.5,22T,1Cr+,3+
2,3,SUGAR Cosmetics: Buy Beauty Products Online,SUGAR Cosmetics,Beauty,13 MB,4.5,42T,10L+,3+
3,4,Men Hair style photo Editor,kobecodder,Beauty,13 MB,3.7,2T,10L+,3+
4,5,"Beauty Makeup Editor: Beauty Camera, Photo Editor",Lyrebird Studio,Beauty,68 MB,3.6,2L,1Cr+,3+

In [9]:
df5= pd.read_csv("Books  Reference.csv")

In [10]:
df5.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,Pratilipi - World of Stories,Pratilipi,Books & Reference,14 MB,4.5,2L,1Cr+,12+
1,2,motesFF Challenge - All motes with dances,vijay sharma,Books & Reference,20 MB,3.8,3T,10L+,3+
2,3,How to Get diamonds in FFF,Ultra HD Video Player,Books & Reference,11 MB,4.1,32T,1Cr+,3+
3,4,Amazon Kindle - eBooks & more,Amazon Mobile LLC,Books & Reference,56 MB,4.6,22L,10Cr+,12+
4,5,Google Play Books,Google LLC,Books & Reference,9.7 MB,4.1,1M,1B+,12+

In [11]:
df6= pd.read_csv("Business.csv")

In [12]:
df6.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,ZOOM Cloud Meetings,zoom.us,Business,41 MB,4.0,3M,500M+,3+
1,2,Google Meet,Google LLC,Business,20 MB,4.1,2M,100M+,3+
2,3,"apna: Job Search, Alerts India",apna,Business,25 MB,4.6,2L,1Cr+,12+
3,4,Microsoft Teams,Microsoft Corporation,Business,64 MB,4.3,4M,100M+,3+
4,5,"Adobe Scan: PDF Scanner, OCR",Adobe,Business,28 MB,4.6,1M,50M+,3+

In [13]:
df7 = pd.read_csv("Comics.csv")

In [14]:
df7.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,Free Comics - Pratilipi Comics,Pratilipi,Comics,6.5 MB,4.3,39T,50L+,12+
1,2,BILIBILI COMICS - Read Comics,Bilibili Comics,Comics,38 MB,4.2,63T,50L+,12+
2,3,Girls Live Video Call – Video Chat,Shree Intersoft,Comics,16 MB,3.5,743,1L+,18+
3,4,WEBTOON,WEBTOON ENTERTAINMENT,Comics,23 MB,4.8,23L,5Cr+,12+
4,5,"Picasso : Live Tv show, Movies and Cricket Guide",Live Life 2021,Comics,6.2 MB,3.0,1T,1L+,3+

In [15]:
df8 = pd.read_csv("EDucation.csv")

In [16]:
df8.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,BYJU'S – The Learning App,BYJU'S,Education,76 MB,4.2,17L,10Cr+,3+
1,2,Brainly — Solve Doubts,Brainly,Education,17 MB,4.3,21L,10Cr+,3+
2,3,Duolingo: Learn English Free,Duolingo,Education,21 MB,4.5,1Cr,10Cr+,3+
3,4,Unacademy Learner App,Unacademy,Education,45 MB,4.0,9L,5Cr+,3+
4,5,Teachmint - Live Classroom App,Teachmint Technologies,Education,19 MB,4.2,1L,1Cr+,3+

In [17]:
df9 = pd.read_csv("Entertainment.csv")

In [18]:
df9.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,Amazon Prime Video,Amazon Mobile LLC,Entertainment,28 MB,4.3,3M,100M+,12+
1,2,"ZEE5:Movies, Web Series & more",Z5X Global FZ LLC,Entertainment,21 MB,3.5,12L,10Cr+,12+
2,3,Hotstar,Novi Digital,Entertainment,23 MB,4.2,10M,500M+,12+
3,4,Zili - Short Video App for India | Funny,Zili,Entertainment,25 MB,4.0,8L,10Cr+,12+
4,5,JioTV,Jio Platforms Limited,Entertainment,16 MB,4.0,35L,10Cr+,3+

In [19]:
df10 = pd.read_csv("Events.csv")

In [20]:
df10.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,Invitation maker & Card design,Greetings Island,Events,26 MB,4.6,89T,1Cr+,3+
1,2,Tournafest,Tournafest Gaming Private Limited,Events,21 MB,4.2,573,50T+,3+
2,3,Video Invitation Maker App,VideoInvites.net,Events,4.6 MB,3.8,1T,5L+,3+
3,4,Wedding Card Maker Indian,Hope & Courage Company,Events,7.5 MB,4.6,1T,1L+,3+
4,5,Kiko Live,Kiko Live,Events,58 MB,4.1,1T,1L+,3+

In [21]:
df11 = pd.read_csv("Finance.csv")

In [22]:
df11.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,"PhonePe: UPI, Recharge, Investment, Insurance",PhonePe,Finance,35 MB,4.3,78L,10Cr+,3+
1,2,"Paytm -UPI, Money Transfer, Recharge, Bill Pay...",Paytm - One97 Communications Ltd.,Finance,31 MB,4.6,1Cr,10Cr+,3+
2,3,Google Pay: Secure UPI payment,Google LLC,Finance,20 MB,4.2,71L,50Cr+,3+
3,4,CoinDCX:Bitcoin Investment App,CoinDCX Official,Finance,22 MB,3.6,2L,1Cr+,3+
4,5,Navi: Loans & Health Insurance,navi.com,Finance,24 MB,3.9,1L,1Cr+,3+

In [23]:
df12 = pd.read_csv("Food  Drink.csv")

In [24]:
df12.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,Zomato: Food Delivery & Dining,Zomato,Food & Drink,21 MB,4.1,60L,10Cr+,3+
1,2,Swiggy : Food Delivery & More,Swiggy,Food & Drink,33 MB,4.0,2M,100M+,3+
2,3,Domino's Pizza - Online Food Delivery App,Jubilant Foodworks,Food & Drink,11 MB,4.6,741K,10M+,3+
3,4,blinkit (formerly grofers),Grofers India Pvt Ltd,Food & Drink,20 MB,4.1,6L,1Cr+,3+
4,5,"Country Delight: Milk Delivery, Vegetable, Gro...",Country Delight,Food & Drink,17 MB,4.7,34T,50L+,12+

In [25]:
df13 = pd.read_csv("Health  Fitness.csv")

In [26]:
df13.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,HealthifyMe - Calorie Counter,"HealthifyMe (Calorie Counter, Weight Loss Coach)",Health & Fitness,44 MB,4.4,3L,1Cr+,3+
1,2,Skin-scan: Hand Protection,3B Gamse Studio,Health & Fitness,49 MB,4.3,2T,5L+,3+
2,3,Aarogya Setu,National Informatics Centre.,Health & Fitness,3.1 MB,3.8,16L,10Cr+,3+
3,4,Mylab CoviSelf,Mylab Discovery Solutions,Health & Fitness,26 MB,2.3,1T,5L+,3+
4,5,Co-WIN Vaccinator App,National Health Portal-MoHFW,Health & Fitness,11 MB,2.8,1L,1Cr+,3+

In [27]:
df14 = pd.read_csv("Health  Fitness.csv")

In [28]:
df14.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,HealthifyMe - Calorie Counter,"HealthifyMe (Calorie Counter, Weight Loss Coach)",Health & Fitness,44 MB,4.4,3L,1Cr+,3+
1,2,Skin-scan: Hand Protection,3B Gamse Studio,Health & Fitness,49 MB,4.3,2T,5L+,3+
2,3,Aarogya Setu,National Informatics Centre.,Health & Fitness,3.1 MB,3.8,16L,10Cr+,3+
3,4,Mylab CoviSelf,Mylab Discovery Solutions,Health & Fitness,26 MB,2.3,1T,5L+,3+
4,5,Co-WIN Vaccinator App,National Health Portal-MoHFW,Health & Fitness,11 MB,2.8,1L,1Cr+,3+

In [29]:
df15 = pd.read_csv("Libraries  Demo.csv")

In [30]:
df15.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,Guide,Tubejet,Libraries & Demo,11 MB,3.9,442,1L+,3+
1,2,MX Player Codec (ARMv7 NEON),MX Media (formerly J2 Interactive),Libraries & Demo,8.1 MB,3.8,4L,5Cr+,3+
2,3,Tap Tap app Apk Games Guide,Kitty Pitty,Libraries & Demo,13 MB,3.6,166,10T+,3+
3,4,V380 Pro,macrovideo,Libraries & Demo,62 MB,3.9,48T,1Cr+,3+
4,5,MFS100 Test,Mantra Softech India Pvt Ltd,Libraries & Demo,3.8 MB,4.2,1T,10L+,3+

In [31]:
df16 = pd.read_csv("Lifestyle.csv")

In [32]:
df16.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,Pinterest,Pinterest,Lifestyle,25 MB,4.4,87L,50Cr+,12+
1,2,ECO Mitram,Ready Bytes,Lifestyle,7.7 MB,4.1,1T,5L+,3+
2,3,magicpin: shop at local stores,magicpin: cashback / home delivery on local re...,Lifestyle,25 MB,4.1,1L,50L+,3+
3,4,Trell - Lifestyle Videos and Shopping App,Trell Experiences,Lifestyle,24 MB,4.4,1L,1Cr+,12+
4,5,Google Home,Google LLC,Lifestyle,19 MB,4.0,11L,10Cr+,3+

In [33]:
df17 = pd.read_csv("Maps  Navigation.csv")

In [34]:
df17.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,what3words,what3words,Maps & Navigation,43 MB,4.0,26T,1Cr+,3+
1,2,"Ola, Safe and affordable rides",ola,Maps & Navigation,31 MB,4.3,19L,10Cr+,3+
2,3,Rapido Bike Taxi & Auto,Rapido Bike Taxi,Maps & Navigation,18 MB,4.0,7L,1Cr+,3+
3,4,CarInfo: RTO Vehicle Information App,Car Info,Maps & Navigation,15 MB,4.5,7L,1Cr+,3+
4,5,Uber - Easy affordable trips,"Uber Technologies, Inc.",Maps & Navigation,64 MB,4.2,94L,50Cr+,3+

In [35]:
df18 = pd.read_csv("Medical.csv")

In [36]:
df18.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,PharmEasy - Healthcare App,Axelia Solutions Private Limited,Medical,18 MB,4.6,5L,1Cr+,3+
1,2,TATA 1mg Online Healthcare App,Tata 1MG Healthcare Solutions Private Limited,Medical,12 MB,4.5,4L,1Cr+,3+
2,3,Netmeds - India Ki Pharmacy,Netmeds Marketplace Limited,Medical,17 MB,4.3,3L,1Cr+,3+
3,4,Apollo 247 - Online Doctor & Apollo Pharmacy App,Apollo Hospitals Enterprise Limited,Medical,37 MB,4.2,1L,50L+,3+
4,5,Phable: Health Tracker for Diabetes & Hyperten...,PhableCare,Medical,51 MB,3.6,24T,10L+,3+

In [37]:
df19 = pd.read_csv("Music  Audio.csv")

In [38]:
df19.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,Gaana Music : Songs & Podcasts,Gamma Gaana Ltd,Music & Audio,31 MB,4.5,45L,10Cr+,12+
1,2,Wynk Music -Songs & HelloTunes,Airtel,Music & Audio,21 MB,4.3,38L,10Cr+,3+
2,3,JioSaavn - Music & Podcasts,Saavn Media Limited,Music & Audio,23 MB,4.2,39L,10Cr+,3+
3,4,Pocket FM: Audiobook & Podcast,Pocket FM,Music & Audio,16 MB,4.2,7L,1Cr+,12+
4,5,Resso Music - Songs & Lyrics,Moon Video Inc.,Music & Audio,48 MB,4.6,14L,10Cr+,12+

In [39]:
df20 = pd.read_csv("News  Magazines.csv")

In [40]:
df20.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,"Dailyhunt - Local & National News, Videos, Cri...",Eterno Infotech,News & Magazines,13 MB,4.4,16L,10Cr+,12+
1,2,"Dainik Bhaskar:Hindi News Paper App, ePaper, V...",Dainik Bhaskar Group,News & Magazines,8.3 MB,4.3,3L,1Cr+,3+
2,3,Aaj Tak Live - Hindi News App,TV Today Network Limited,News & Magazines,14 MB,4.0,2L,5Cr+,3+
3,4,"Narendra Modi - Latest News, Videos and Speeches",NarendraModi.in,News & Magazines,47 MB,4.4,2L,1Cr+,3+
4,5,Koo: Connect with People!,Koo India,News & Magazines,16 MB,4.5,2L,1Cr+,12+

In [41]:
df21 = pd.read_csv("Parenting.csv")

In [42]:
df21.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,"Indian Pregnancy, Parenting Tips & Baby Products","Indian Pregnancy Parenting tips, Baby products...",Parenting,19 MB,4.6,80T,1Cr+,12+
1,2,Mylo Pregnancy & Parenting App,Mylo - Indian Pregnancy Tracker & Baby Care App,Parenting,16 MB,4.6,70T,10L+,3+
2,3,LastLog-Last Seen Online Tracker,LastLog Inc.,Parenting,13 MB,4.1,8T,1L+,3+
3,4,"Pregnancy + | tracker app, week by week in 3D",Philips Digital UK Limited,Parenting,50 MB,4.4,17L,1Cr+,3+
4,5,Top Parent - New Ways of Learning And Teaching,Humanitus,Parenting,2.6 MB,4.1,512,1L+,3+

In [43]:
df22 = pd.read_csv("Personalisation.csv")

In [44]:
df22.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,"iFonts - highlights cover, fonts, wallpapers",Onbillion Ltd,Personalisation,19 MB,2.9,6T,1Cr+,3+
1,2,ZEDGE™ Wallpapers & Ringtones,Zedge,Personalisation,28 MB,4.3,95L,10Cr+,12+
2,3,Name Ringtone Maker,DoubleRun Technology,Personalisation,5.5 MB,3.8,8T,1Cr+,3+
3,4,MobCup Ringtones & Wallpapers,MobCup,Personalisation,13 MB,4.3,21T,50L+,12+
4,5,Fonts Keyboard,Fonts Keyboard,Personalisation,5.1 MB,4.3,8L,5Cr+,3+

In [45]:
df23 = pd.read_csv("Photography.csv")

In [46]:
df23.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,Video Editor & Maker - InShot,InShot Video Editor,Photography,53 MB,4.6,1Cr,10Cr+,3+
1,2,EPIK - Photo Editor,"SNOW, Inc.",Photography,83 MB,4.2,30T,50L+,12+
2,3,"Instore: Story Saver, Story, Video Downloader",Apps for Creators,Photography,24 MB,4.3,4L,1Cr+,3+
3,4,Picsart Photo and Video Editor,"PicsArt, Inc.",Photography,43 MB,4.2,1Cr,50Cr+,12+
4,5,Snapseed,Google LLC,Photography,24 MB,4.3,14L,10Cr+,3+

In [47]:
df24 = pd.read_csv("Productivity.csv")

In [48]:
df24.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,MyJio: For Everything Jio,Jio Platforms Limited,Productivity,42 MB,4.3,1Cr,10Cr+,3+
1,2,"Airtel Thanks – Recharge, Bill Pay, UPI & Bank",Airtel,Productivity,30 MB,4.3,57L,10Cr+,3+
2,3,"Share Karo: Transfer, Share it",ShareKaro Team,Productivity,12 MB,4.3,53T,1Cr+,3+
3,4,Junk Smasher - Phone Cleaner,InnoDev Pro Team,Productivity,11 MB,4.1,87T,1Cr+,3+
4,5,Global- Fast VPN Proxy Servers,BaronBaron,Productivity,10 MB,3.4,3T,50L+,3+

In [49]:
df25 = pd.read_csv("Shopping.csv")

In [50]:
df25.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,Meesho: Online Shopping App,Meesho,Shopping,14 MB,4.4,15L,10Cr+,3+
1,2,Shopee: Online Shopping,Shopee,Shopping,68 MB,4.2,86T,1Cr+,3+
2,3,Flipkart Online Shopping App,Flipkart,Shopping,18 MB,4.3,2Cr,10Cr+,12+
3,4,Shopsy Shopping App - Flipkart,Shopsy,Shopping,17 MB,4.3,3L,1Cr+,3+
4,5,Amazon India - Shop & Pay,Amazon Mobile LLC,Shopping,57 MB,4.2,79L,10Cr+,3+

In [51]:
df26 = pd.read_csv("Social.csv")

In [52]:
df26.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,Instagram,Instagram,Social,40 MB,4.3,13Cr,100Cr+,12+
1,2,Chingari - powered by GARI,Chingari,Social,56 MB,3.8,4L,5Cr+,12+
2,3,Facebook,"Meta Platforms, Inc.",Social,51 MB,4.1,12Cr,500Cr+,12+
3,4,Rizzle - Short Video Maker,"Silverlabs Technologies, Inc.",Social,43 MB,4.3,2L,1Cr+,12+
4,5,Josh: Short Videos App,Ver Se Innovation,Social,38 MB,4.1,6L,10Cr+,12+

In [53]:
df27 = pd.read_csv("Sports.csv")

In [54]:
df27.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,Rooter: Watch Gaming & Esports,Rooter Sports,Sports,26 MB,4.3,3L,1Cr+,12+
1,2,Da Fit,CRREPA,Sports,8.5 MB,3.9,86T,1Cr+,3+
2,3,Live Cricket & Scores: FanCode,Sporta Technologies Private Limited,Sports,27 MB,4.1,1L,1Cr+,12+
3,4,Cricket Scoring App | Live Score - CricHeroes,CricHeroes Pvt. Ltd.,Sports,19 MB,4.6,97T,50L+,3+
4,5,iMPL Game - Play Games & Earn Money From iMPL ...,iMPL Game,Sports,8.6 MB,3.7,2T,10L+,3+

In [55]:
df28 = pd.read_csv("Tools.csv")

In [56]:
df28.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,speedfiy Pro,PRIME DIGITAL PTE. LTD.,Tools,13 MB,4.4,31K,5M+,3+
1,2,All Video Downloader,All Video Downloader & Story Saver Apps,Tools,7.2 MB,4.2,49T,1Cr+,3+
2,3,ShareKaro: File Sharing,ShareKaro Team,Tools,14 MB,4.4,2L,5Cr+,3+
3,4,Noizz: video editor with music,Noizz Team,Tools,37 MB,4.0,5L,10Cr+,12+
4,5,speedfiy,PRIME DIGITAL PTE. LTD.,Tools,12 MB,4.4,45T,1Cr+,3+

In [57]:
df29 = pd.read_csv("Travel  Local.csv")

In [58]:
df29.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,Where is my Train,Sigmoid Labs and its Affiliates,Travel & Local,10 MB,4.4,29L,10Cr+,3+
1,2,Train Status Ticket Book PNR,"ixigo - IRCTC Authorised Partner, Flight Tickets",Travel & Local,18 MB,4.4,19L,10Cr+,3+
2,3,IRCTC Rail Connect,IRCTC Official,Travel & Local,16 MB,4.0,22L,5Cr+,3+
3,4,ConfirmTkt - Train Booking,ConfirmTkt - IRCTC Authorised Partner,Travel & Local,14 MB,4.6,4L,1Cr+,3+
4,5,Google Earth,Google LLC,Travel & Local,8.6 MB,4.4,28L,10Cr+,3+

In [59]:
df30 = pd.read_csv("Video Players  Editors.csv")

In [60]:
df30.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,"MX Player: Videos, OTT & Games",MX Media (formerly J2 Interactive),Video Players & Editors,36 MB,4.1,1Cr,100Cr+,3+
1,2,mAst: Music Status Video Maker,Mast Team,Video Players & Editors,65 MB,4.3,2L,5Cr+,3+
2,3,Mivita - Face Swap Video Maker,vakie,Video Players & Editors,64 MB,3.2,6T,10L+,3+
3,4,PLAYit-All in One Video Player,PLAYIT TECHNOLOGY PTE. LTD.,Video Players & Editors,14 MB,4.5,35L,10Cr+,3+
4,5,Mivi:Music&Lyrical Video Maker,Music Video Studio,Video Players & Editors,44 MB,4.3,1L,1Cr+,3+

In [61]:
df = pd.concat([df2, df3,  df5,df6,df7,df8,df9,df10,df11,df12,df13,df14,df15,df16,df17,df18,df19,df20,df21,df22,df23,df24,df25,df26,df27,df28,df29,df30], ignore_index=True)

In [62]:
df.head()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
0,1,RTO Vehicle Information,Learn English In Hindi - Translator & Dictionary,Auto & Vehicles,21 MB,4.5,1L,1Cr+,3+
1,2,"Vahak: Book Online Truck, Load",Most Trusted Transporters from All India.,Auto & Vehicles,17 MB,3.8,3T,10L+,3+
2,3,"CARS24® – Buy Used Cars Online, Sell Car in 1 ...",CARS24 Services Private Limited,Auto & Vehicles,33 MB,4.4,1L,1Cr+,3+
3,4,BlackBuck Boss,BlackBuck,Auto & Vehicles,39 MB,4.1,27T,10L+,3+
4,5,CarDekho:New & Second Hand Car,Girnar Software Pvt. Ltd.,Auto & Vehicles,18 MB,4.5,1L,1Cr+,3+

In [64]:
df.shape

(13928, 9)

In [65]:
df.tail()

,Rank,Name,Developer,Category,Size,Star Rating,Reviews,Downloads,Rated for
13923,496,"Video Hider - Photo Vault, Video Downloader",Photo Editor & Collage Maker,Video Players & Editors,11 MB,4.1,32T,50L+,3+
13924,497,Video Downloader,Vid Dl,Video Players & Editors,11 MB,3.1,291,1L+,3+
13925,498,Video Maker with Music 2022,Photo Slideshow & Photo Video Maker,Video Players & Editors,16 MB,4.4,8T,10L+,3+
13926,499,"Private Photo, Video Locker",Kohinoor Apps,Video Players & Editors,9.2 MB,4.3,2L,1Cr+,3+
13927,500,Video player,atbcstd,Video Players & Editors,23 MB,3.9,11T,10L+,3+

In [66]:
df.to_csv('app_data.csv')